services:
  ci-tools:
    image: ci-tools:local
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        NPM_VERSION: ${NPM_VERSION}
        SHFMT_AMD64_URL: ${SHFMT_AMD64_URL}
        SHFMT_AMD64_SHA256: ${SHFMT_AMD64_SHA256}
        SHFMT_ARM64_URL: ${SHFMT_ARM64_URL}
        SHFMT_ARM64_SHA256: ${SHFMT_ARM64_SHA256}
        ACTIONLINT_AMD64_URL: ${ACTIONLINT_AMD64_URL}
        ACTIONLINT_AMD64_SHA256: ${ACTIONLINT_AMD64_SHA256}
        ACTIONLINT_ARM64_URL: ${ACTIONLINT_ARM64_URL}
        ACTIONLINT_ARM64_SHA256: ${ACTIONLINT_ARM64_SHA256}
        HADOLINT_AMD64_URL: ${HADOLINT_AMD64_URL}
        HADOLINT_AMD64_SHA256: ${HADOLINT_AMD64_SHA256}
        HADOLINT_ARM64_URL: ${HADOLINT_ARM64_URL}
        HADOLINT_ARM64_SHA256: ${HADOLINT_ARM64_SHA256}
        YQ_AMD64_URL: ${YQ_AMD64_URL}
        YQ_AMD64_SHA256: ${YQ_AMD64_SHA256}
        YQ_ARM64_URL: ${YQ_ARM64_URL}
        YQ_ARM64_SHA256: ${YQ_ARM64_SHA256}
        GH_AMD64_URL: ${GH_AMD64_URL}
        GH_AMD64_SHA256: ${GH_AMD64_SHA256}
        GH_ARM64_URL: ${GH_ARM64_URL}
        GH_ARM64_SHA256: ${GH_ARM64_SHA256}
        SHELLCHECK_AMD64_URL: ${SHELLCHECK_AMD64_URL}
        SHELLCHECK_AMD64_SHA256: ${SHELLCHECK_AMD64_SHA256}
        SHELLCHECK_ARM64_URL: ${SHELLCHECK_ARM64_URL}
        SHELLCHECK_ARM64_SHA256: ${SHELLCHECK_ARM64_SHA256}
        JQ_AMD64_URL: ${JQ_AMD64_URL}
        JQ_AMD64_SHA256: ${JQ_AMD64_SHA256}
        JQ_ARM64_URL: ${JQ_ARM64_URL}
        JQ_ARM64_SHA256: ${JQ_ARM64_SHA256}
        LUACHECK_VERSION: ${LUACHECK_VERSION}
        BUSTED_VERSION: ${BUSTED_VERSION}
        BATS_VERSION: ${BATS_VERSION}
        BATS_COMMIT: ${BATS_COMMIT}
        BATS_SUPPORT_VERSION: ${BATS_SUPPORT_VERSION}
        BATS_SUPPORT_COMMIT: ${BATS_SUPPORT_COMMIT}
        BATS_ASSERT_VERSION: ${BATS_ASSERT_VERSION}
        BATS_ASSERT_COMMIT: ${BATS_ASSERT_COMMIT}
        BATS_FILE_VERSION: ${BATS_FILE_VERSION}
        BATS_FILE_COMMIT: ${BATS_FILE_COMMIT}
        VALIDATE_ACTION_PINS_VERSION: ${VALIDATE_ACTION_PINS_VERSION}
